# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fpopTreeTransfer <- function(vectData, tree_t, type, vectWeight, testMode) {
    .Call(`_fpopTree_fpopTreeTransfer`, vectData, tree_t, type, vectWeight, testMode)
}

